---
- hosts: docker
  vars_prompt:
  - name: username
    private: no
    prompt: "Provide username"
    default: "grza"
  become: yes
  tasks:
    
    - name: Install docker dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    
    - name: Add GPG keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
    
    - name: Make sure docker was started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add group for docker
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ username }}"
        append: yes
        group: docker
    
  handlers:
    - name: Restart docker
      service: 
        name: docker 
        state: restarted
