---
- name: Setup dev system
  hosts: localhost
  vars_prompt:
    - name: python_short_version
      private: no
      prompt: "Python version to install (only one dot)"
      default: "3.10"

    - name: python_short_long
      private: no
      prompt: "Python version to install (full version)"
      default: "3.10.4"

    - name: username
      private: no
      prompt: "Provide username"
      default: "grza"

  roles:
    - role: diodonfrost.python
      become: yes
      vars:
        python_version: {{ python_short_long }}
        python_path: "/usr/local/python{{ python_short_version }}" # TODO: change later to default when issue resolved
        
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 86400 # One day

    - name: Add python alias for my user
      lineinfile:
        path=/home/{{ username }}/.bashrc
        line="alias python='/usr/local/python{{ python_short_version }}/bin/python{{ python_short_version }}'" 
        state=present
        insertafter=EOF
        create=True 

    - name: Add relative line numbers in vi
      lineinfile:
        path=/home/{{ username }}/.vimrc
        line="set relativenumber"
        state=present
        insertafter=EOF
        create=True